/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#171717',
        ink: '#171717',
        body: '#4d4d4d',
        mute: '#888888',
        hairline: '#ebebeb',
        'hairline-strong': '#a1a1a1',
        canvas: '#ffffff',
        'canvas-soft': '#fafafa',
        'canvas-soft-2': '#f5f5f5',
        link: '#0070f3',
        'link-deep': '#0761d1',
        'link-bg-soft': '#d3e5ff',
        success: '#0070f3',
        error: '#ee0000',
        'error-soft': '#f7d4d6',
        'error-deep': '#c50000',
        warning: '#f5a623',
        'warning-soft': '#ffefcf',
        'warning-deep': '#ab570a',
        violet: '#7928ca',
        'violet-soft': '#d8ccf1',
        'violet-deep': '#4c2889',
        cyan: '#50e3c2',
        'cyan-soft': '#aaffec',
        'cyan-deep': '#29bc9b',
        'highlight-pink': '#ff0080',
        'highlight-magenta': '#eb367f',
        'gradient-develop-start': '#007cf0',
        'gradient-develop-end': '#00dfd8',
        'gradient-preview-start': '#7928ca',
        'gradient-preview-end': '#ff0080',
        'gradient-ship-start': '#ff4d4d',
        'gradient-ship-end': '#f9cb28',
      },
      borderRadius: {
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        'pill-sm': '64px',
        pill: '100px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '40px',
        '3xl': '48px',
        '4xl': '64px',
        '5xl': '96px',
        '6xl': '128px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'monospace'],
      },
      typography: {
        'display-xl': {
          fontFamily: 'Inter, system-ui, sans-serif',
          fontSize: '48px',
          fontWeight: '600',
          lineHeight: '48px',
          letterSpacing: '-2.4px',
        },
        'display-lg': {
          fontFamily: 'Inter, system-ui, sans-serif',
          fontSize: '32px',
          fontWeight: '600',
          lineHeight: '40px',
          letterSpacing: '-1.28px',
        },
        'display-md': {
          fontFamily: 'Inter, system-ui, sans-serif',
          fontSize: '24px',
          fontWeight: '600',
          lineHeight: '32px',
          letterSpacing: '-0.96px',
        },
        'display-sm': {
          fontFamily: 'Inter, system-ui, sans-serif',
          fontSize: '20px',
          fontWeight: '600',
          lineHeight: '28px',
          letterSpacing: '-0.6px',
        },
        'body-lg': {
          fontFamily: 'Inter, system-ui, sans-serif',
          fontSize: '18px',
          fontWeight: '400',
          lineHeight: '28px',
        },
        'body-md': {
          fontFamily: 'Inter, system-ui, sans-serif',
          fontSize: '16px',
          fontWeight: '400',
          lineHeight: '24px',
        },
        'body-md-strong': {
          fontFamily: 'Inter, system-ui, sans-serif',
          fontSize: '16px',
          fontWeight: '500',
          lineHeight: '24px',
        },
        'body-sm': {
          fontFamily: 'Inter, system-ui, sans-serif',
          fontSize: '14px',
          fontWeight: '400',
          lineHeight: '20px',
          letterSpacing: '-0.28px',
        },
        'body-sm-strong': {
          fontFamily: 'Inter, system-ui, sans-serif',
          fontSize: '14px',
          fontWeight: '500',
          lineHeight: '20px',
          letterSpacing: '-0.28px',
        },
        caption: {
          fontFamily: 'Inter, system-ui, sans-serif',
          fontSize: '12px',
          fontWeight: '400',
          lineHeight: '16px',
        },
        'caption-mono': {
          fontFamily: 'JetBrains Mono, ui-monospace, monospace',
          fontSize: '12px',
          fontWeight: '400',
          lineHeight: '16px',
        },
        code: {
          fontFamily: 'JetBrains Mono, ui-monospace, monospace',
          fontSize: '13px',
          fontWeight: '400',
          lineHeight: '20px',
        },
      },
      boxShadow: {
        'level-1': '0 0 0 1px rgba(0, 0, 0, 0.086)',
        'level-2': '0 1px 1px rgba(0, 0, 0, 0.031), 0 2px 2px rgba(0, 0, 0, 0.062), inset 0 0 0 1px rgba(0, 0, 0, 0.086)',
        'level-3': '0 2px 2px rgba(0, 0, 0, 0.062), 0 8px 8px -8px rgba(0, 0, 0, 0.062), inset 0 0 0 1px rgba(0, 0, 0, 0.086)',
        'level-4': '0 2px 2px rgba(0, 0, 0, 0.062), 0 8px 16px -4px rgba(0, 0, 0, 0.062), inset 0 0 0 1px rgba(0, 0, 0, 0.086)',
        'level-5': '0 1px 1px rgba(0, 0, 0, 0.031), 0 8px 16px -4px rgba(0, 0, 0, 0.062), 0 24px 32px -8px rgba(0, 0, 0, 0.094), inset 0 0 0 1px rgba(0, 0, 0, 0.086)',
      },
    },
  },
  plugins: [],
}
